"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_count = {}
        t_count = {}

        for word in s:
            if word not in s_count:
                s_count[word] = 0
            s_count[word] += 1

        for word in t:
            if word not in t_count:
                t_count[word] = 0
            t_count[word] += 1

        diff = []
        for word in t_count:
            if word in s_count:
                for i in range(t_count[word] - s_count[word]):
                    diff.append(word)
            else:
                for i in range(t_count[word]):
                    diff.append(word)
        return ''.join(diff)

sol = Solution()
s = "abcd"
t = "abcde"
print(sol.findTheDifference(s, t))
